import time
import requests
import socket
import ssl
import datetime
from bs4 import BeautifulSoup
from fpdf import FPDF
from web3 import Web3
from urllib.parse import urlparse

class VanguardAuditor:
    def __init__(self, rpc_url):
        self.w3 = Web3(Web3.HTTPProvider(rpc_url))

    def analyze_target(self, target):
        if target.startswith("http") or "www" in target:
            return self.audit_website(target)
        elif target.startswith("0x") and len(target) == 42:
            return self.audit_wallet(target)
        else:
            return None, "Invalid Target"

    def audit_website(self, url):
        if not url.startswith("http"): url = "https://" + url
        report = []
        issues = 0
        fix_price = 0

        try:
            start = time.time()
            r = requests.get(url, timeout=10)
            speed = round(time.time() - start, 2)

            # 1. SPEED CHECK
            if speed > 1.5:
                report.append(f"CRITICAL: Load time {speed}s. Losing customers.")
                issues += 1
                fix_price += 200
            else:
                report.append(f"PASS: Speed optimal ({speed}s).")

            # 2. SSL CHECK
            hostname = urlparse(url).netloc
            try:
                ctx = ssl.create_default_context()
                with ctx.wrap_socket(socket.socket(), server_hostname=hostname) as s:
                    s.connect((hostname, 443))
                    cert = s.getpeercert()
                report.append("PASS: SSL Certificate Valid.")
            except:
                report.append("CRITICAL: SSL Invalid/Expired. Site is 'Not Secure'.")
                issues += 1
                fix_price += 150

            # 3. SEO CHECK
            soup = BeautifulSoup(r.text, 'html.parser')
            if not soup.find("meta", attrs={"name": "description"}):
                report.append("RISK: Missing SEO Tags. Invisible to Google.")
                issues += 1
                fix_price += 100

        except Exception as e:
            report.append(f"FATAL: Site unreachable. {str(e)}")
            issues += 5
            fix_price += 500

        admin_brief = f"🛠 **QUOTE:** ${fix_price + 100}\nTarget: {url}\nIssues: {issues}"
        pdf = self.generate_pdf("WEBSITE", url, report)
        return pdf, admin_brief

    def audit_wallet(self, wallet):
        report = []
        try:
            bal = self.w3.from_wei(self.w3.eth.get_balance(wallet), 'ether')
            tx_count = self.w3.eth.get_transaction_count(wallet)
            report.append(f"Wallet: {wallet}")
            report.append(f"Balance: {bal:.4f} ETH")
            report.append(f"Nonce: {tx_count}")
            if tx_count == 0: report.append("STATUS: Inactive Wallet")
            else: report.append("STATUS: Active Trader")
        except: report.append("Error scanning blockchain.")

        pdf = self.generate_pdf("WALLET", wallet, report)
        return pdf, f"🔍 WALLET SCAN: {wallet}"

    def generate_pdf(self, type, target, lines):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt="VANGUARD SECURITY AUDIT", ln=1, align='C')
        pdf.cell(200, 10, txt=f"Target: {target} [{type}]", ln=1, align='C')
        pdf.ln(10)
        for line in lines:
            pdf.multi_cell(0, 10, txt=line)
        pdf.ln(20)
        pdf.cell(0, 10, txt="Generated by IceReign Systems.", ln=1, align='C')
        filename = f"audit_{int(time.time())}.pdf"
        pdf.output(filename)
        return filename
